spring.application.name: ShareApi
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/**.xml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          auth-client:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            provider: vaulty-auth
        provider:
          vaulty-auth:
            token-uri: http://localhost:8080/api/token
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: auth-client

vaulty:
  auth.url: http://localhost:8080
  client.id: ${CLIENT_ID}
  scopes: api.share.app

server:
  port: 8081